language: python
dist: xenial
matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
addons:
  apt:
    packages:
      - sox
      - libsox-fmt-mp3
      - ffmpeg
      - mediainfo
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install backports.tempfile  # Python 2.7
script:
  - python -m pytest
